// Curated figlet set. `ascii: false` fonts use block / box-drawing glyphs
// and exist to demonstrate the 7-bit guard; every other one renders
// identically on Windows, latin-1 files and old terminals.
export const FONTS = [
    { id: 'Standard', name: 'Standard', ascii: true, h: 6, tags: ['classique'] },
    { id: 'Big', name: 'Big', ascii: true, h: 8, tags: ['classique'] },
    { id: 'Slant', name: 'Slant', ascii: true, h: 6, tags: ['classique'] },
    { id: 'Small', name: 'Small', ascii: true, h: 5, tags: ['compact'] },
    { id: 'Small Slant', name: 'Small Slant', ascii: true, h: 5, tags: ['compact'] },
    { id: 'Banner', name: 'Banner', ascii: true, h: 8, tags: ['bloc'] },
    { id: 'Block', name: 'Block', ascii: true, h: 8, tags: ['bloc'] },
    { id: 'Doom', name: 'Doom', ascii: true, h: 8, tags: ['classique'] },
    { id: 'Mini', name: 'Mini', ascii: true, h: 4, tags: ['compact'] },
    { id: 'Shadow', name: 'Shadow', ascii: true, h: 5, tags: ['classique'] },
    { id: 'Ogre', name: 'Ogre', ascii: true, h: 6, tags: ['classique'] },
    { id: 'Script', name: 'Script', ascii: true, h: 7, tags: ['fantaisie'] },
    { id: 'Larry 3D', name: 'Larry 3D', ascii: true, h: 9, tags: ['3d'] },
    { id: 'Star Wars', name: 'Star Wars', ascii: true, h: 7, tags: ['bloc'] },
    { id: 'Colossal', name: 'Colossal', ascii: true, h: 11, tags: ['bloc'] },
    { id: 'Cybermedium', name: 'Cybermedium', ascii: true, h: 4, tags: ['compact'] },
    { id: 'Cyberlarge', name: 'Cyberlarge', ascii: true, h: 4, tags: ['compact'] },
    { id: 'Speed', name: 'Speed', ascii: true, h: 6, tags: ['fantaisie'] },
    { id: 'Rectangles', name: 'Rectangles', ascii: true, h: 6, tags: ['compact'] },
    { id: 'Chunky', name: 'Chunky', ascii: true, h: 5, tags: ['bloc'] },
    { id: 'Roman', name: 'Roman', ascii: true, h: 10, tags: ['fantaisie'] },
    { id: 'Isometric1', name: 'Isometric', ascii: true, h: 11, tags: ['3d'] },
    { id: 'Graffiti', name: 'Graffiti', ascii: true, h: 6, tags: ['fantaisie'] },
    { id: 'Epic', name: 'Epic', ascii: true, h: 9, tags: ['fantaisie'] },
    { id: 'Sub-Zero', name: 'Sub-Zero', ascii: true, h: 6, tags: ['bloc'] },
    { id: 'Thin', name: 'Thin', ascii: true, h: 6, tags: ['compact'] },
    { id: 'Straight', name: 'Straight', ascii: true, h: 4, tags: ['compact'] },
    { id: 'Stick Letters', name: 'Stick Letters', ascii: true, h: 4, tags: ['compact'] },
    { id: 'Digital', name: 'Digital', ascii: true, h: 3, tags: ['compact'] },
    { id: '3-D', name: '3-D', ascii: true, h: 8, tags: ['3d'] },
    { id: '3D-ASCII', name: '3D-ASCII', ascii: true, h: 10, tags: ['3d'] },
    { id: 'Modular', name: 'Modular', ascii: true, h: 7, tags: ['bloc'] },
    { id: 'Soft', name: 'Soft', ascii: true, h: 7, tags: ['fantaisie'] },
    { id: 'Lean', name: 'Lean', ascii: true, h: 8, tags: ['classique'] },
    { id: 'Bulbhead', name: 'Bulbhead', ascii: true, h: 4, tags: ['compact'] },
    { id: 'Ghost', name: 'Ghost', ascii: true, h: 9, tags: ['fantaisie'] },
    { id: 'Nancyj', name: 'Nancyj', ascii: true, h: 8, tags: ['bloc'] },
    { id: 'Gothic', name: 'Gothic', ascii: true, h: 9, tags: ['fantaisie'] },
    { id: 'Basic', name: 'Basic', ascii: true, h: 8, tags: ['bloc'] },
    { id: 'Banner3', name: 'Banner3', ascii: true, h: 7, tags: ['bloc'] },
    { id: 'Slant Relief', name: 'Slant Relief', ascii: true, h: 9, tags: ['3d'] },
    { id: 'Varsity', name: 'Varsity', ascii: true, h: 7, tags: ['fantaisie'] },
    { id: 'Puffy', name: 'Puffy', ascii: true, h: 8, tags: ['fantaisie'] },
    { id: 'Rounded', name: 'Rounded', ascii: true, h: 7, tags: ['classique'] },
    { id: 'Tombstone', name: 'Tombstone', ascii: true, h: 5, tags: ['compact'] },
    { id: 'Wavy', name: 'Wavy', ascii: true, h: 4, tags: ['compact'] },
    { id: 'Weird', name: 'Weird', ascii: true, h: 6, tags: ['fantaisie'] },
    { id: 'Term', name: 'Term', ascii: true, h: 1, tags: ['compact'] },
    { id: 'ANSI Shadow', name: 'ANSI Shadow', ascii: false, h: 7, tags: ['unicode'] },
    { id: 'Bloody', name: 'Bloody', ascii: false, h: 10, tags: ['unicode'] },
    { id: 'Calvin S', name: 'Calvin S', ascii: false, h: 3, tags: ['unicode'] },
    { id: 'Pagga', name: 'Pagga', ascii: false, h: 3, tags: ['unicode'] },
    { id: 'DOS Rebel', name: 'DOS Rebel', ascii: false, h: 11, tags: ['unicode'] },
    { id: 'Elite', name: 'Elite', ascii: false, h: 5, tags: ['unicode'] },
    { id: 'Delta Corps Priest 1', name: 'Delta Corps Priest', ascii: false, h: 9, tags: ['unicode'] },
];

export const DEFAULT_FONT = 'Standard';

export function findFont(id) {
    return FONTS.find((font) => font.id === id) ?? FONTS[0];
}
